language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  # la configuracion de travis tiene yarn
  - yarn build

notifications:
  email:
    recipients:
      - ala1289@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages # github pages
  skip_clean: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: 'deploy on project'
  on:
    branch: master
